### ISSUE TITLE
加载皮肤闪退

### ISSUE THREAD

**Issue by Timekiller** [Lssg97/DetailedSystemMonitor#10]
5月以后开机rainmeter突然就打不开了，我刚还以为是软件的问题，最后卸载了所有皮肤，一个皮肤一个皮肤启用，才发现是这个皮肤的问题，在论坛、github下载了最新版依然加载闪退。

**Comment by Lssg97** [comment]
这个问题比较复杂，首先确认一下是否对皮肤进行过编辑？先尝试删除 `@Resources\Includes\Config.inc` 后重新安装一下皮肤

**Comment by Timekiller** [comment]
我把整个皮肤全删了，包括皮肤文件夹里@backup里的都删了，@V字头的插件文件夹也删了，重新下的最新版，安装完rainmeter就闪退，就算下面4个插件框框不勾选也不行。

**Comment by Timekiller** [comment]
3.3，3.2，3.1版本我也都试了下，反正只要安装完这个皮肤，rainmeter就打不开了。之前用这个皮肤用了很久，一直好好的，几天前什么也没弄，就正常开机rainmeter就打不开，我开始还以为是软件问题，重新装了好几遍rainmeter。

**Comment by Timekiller** [comment]
作者大大如果可能的话可以加我QQ远程看下？

**Comment by Timekiller** [comment]
感谢大佬已帮我解决，原因是windows中性能监视器维护的计算机数据库坏了，用官网的重建数据库命令解决了，谢谢作者的耐心指导，皮肤很好用，点赞！
