### ISSUE TITLE
ROM 什么意思？应该是IO吧？

### ISSUE THREAD

**Issue by zhaocai** [Lssg97/DetailedSystemMonitor#11]
ROM 不是指代 Read Only Memory 吗？为什么这里会用来指代DISK IO呢？

**Comment by Lssg97** [comment]
只是为了和上面的字符数量保持一致而已。根据我所知道的知识：“ROM”曾经代表着断电后可保存数据的只读存储器，随着存储芯片的几代发展，现在也可以代指可擦除的 Flash 闪存了，进而变成了“存储”的代名词。因为目前大家的电脑基本都是 HDD 和 SSD 混合使用，所以本皮肤干脆就使用了“ROM”这个缩写来代表存储。

　　如果您非常在意这个细节，可以修改本皮肤主配置文件的的 [**7608**](https://github.com/Lssg97/DetailedSystemMonitor/blob/main/Skin/DetailedSystemMonitor.ini#L7608) 行和 [**9457**](https://github.com/Lssg97/DetailedSystemMonitor/blob/main/Skin/DetailedSystemMonitor.ini#L9457) 行，将其中的“ROM”改成自己喜欢的字符串。

**Comment by zhaocai** [comment]
多谢回答，只是一时奇怪。

多说两句：Flash 闪存是因为用在BIOS等，有只读特性所以也能叫ROM，据我所知ROM`进而变成了“存储”的代名词`应该是没有的事，SSD是Solid-state drive，和只读没有一点关系。如果是为了对称，个人建议用I/O指代比较准确：
![shot](https://user-images.githubusercontent.com/341473/177073761-2c7e3667-838c-4bb6-835e-f9ce2b554697.jpg)
