### ISSUE TITLE
温度获取不了，所有的步骤都正确。

### ISSUE THREAD

**Issue by mikuQ** [Lssg97/DetailedSystemMonitor#14]
![AIDA64](https://user-images.githubusercontent.com/71710307/212868790-bf1db62e-5d5f-40a0-9f5a-f33bafdfd827.png)

**Comment by Lssg97** [comment]
您好，先看看 Rainmeter 日志里有没有什么报错

**Comment by mikuQ** [comment]
> 您好，先看看 Rainmeter 日志里有没有什么报错

作者您好，我加你QQ了，没有回应捏。
日志我贴出来你帮忙看看，好像没有报错信息。

[Rainmeter.log](https://github.com/Lssg97/DetailedSystemMonitor/files/10442533/Rainmeter.log)

![CPU温度数值0](https://user-images.githubusercontent.com/71710307/213094434-3fc79764-8b82-44a1-9b4c-324b1e23c8c6.png)
![日志图片](https://user-images.githubusercontent.com/71710307/213094448-9332922c-c977-4990-aa49-5c3689a10c6b.png)

**Comment by mikuQ** [comment]
![image](https://user-images.githubusercontent.com/71710307/213136235-91fa30ec-0283-4bcd-973e-285bdec8aaa6.png)
谢谢作者耐心指导哈，将就着用了。

@温度问题：

下载一个CoreTemp在后台再运行
皮肤部分 编辑配置文件
改1461行Plugin =CPUTemp
改成Plugin=CoreTemp
刷新皮肤

@Xe核显的容量和温度能显示么，如果不能，容量和温度能不能删了，或者可以给定固定数值么

皮肤配置文件里
[MeterGPUTempText]
[MeterGPUTemp]
[Image VRAM]
[MaterVRAMBarContainer]
[MeterVRAMBar]
[MeterVRAMTotal]
[MeterVRAMUserPercentual]
[MeterVRAMFree]
这八个节点 每个后面添加一行Hidden=1

固定值
2192行找到Nun
改成你想要的字符串
Text "Nun"
Text "128MB"
