### ISSUE TITLE
请问在笔记本上怎么让gpu监测只监测核显

### ISSUE THREAD

**Issue by dust07007** [Lssg97/DetailedSystemMonitor#18]
RT，监测独显会激活独显

**Comment by Lssg97** [comment]
> RT，监测独显会激活独显

您好，

　　如果您的电脑同时包含独显和核显，正常情况下 Rainmeter 是不会调用独显来绘制皮肤的，本皮肤也只会被动的获取显卡的工作状态，并不会主动触发独显工作。所以您提到的“监测独显会激活独显”并不成立。如果您坚持这么认为，希望您能提供一些截图支持您的观点。

　　独显工作只有两种情况：一个是有其它进程正在使用独显工作；还有一种情况是您在显卡的控制台里将 Rainmeter 设置成了“高性能”模式（NVIDIA 显卡的叫法），如果您使用的是 NVIDIA 显卡可以按找下图检查看一下。

<img width="779" alt="image" src="https://user-images.githubusercontent.com/47817993/233763898-7a30c31d-a8db-46cd-aef3-1f1e42a3be6f.png">

　　如果您坚持让皮肤屏蔽监测独显的状态，可以查看皮肤的第 2184 行：
https://github.com/Lssg97/DetailedSystemMonitor/blob/59a1389344f367ed5048690fc351fe5538f67b06/Skin/DetailedSystemMonitor.ini#L2184
Intel 核心显卡将其修改为：`String=Intel,,10`；AMD 核心显卡将其修改为：`String=AMD,,10`，这样即可屏蔽对独立显卡的监测。

**Comment by dust07007** [comment]
好的，非常感谢解答
