### ISSUE TITLE
无法获取CPU温度

### ISSUE THREAD

**Issue by lbopenwrt** [Lssg97/DetailedSystemMonitor#2]
更新插件后，CPU温度显示N/A，获取不到，不知道是不是我没安装什么插件所导致的吗？加载皮肤时候已经勾选CPUTemp.dll了。求大佬指导。

**Comment by Lssg97** [comment]
是否使用管理员模式运行了？请参考问题解答第6条。

**Comment by lbopenwrt** [comment]
收到，感谢。冒昧问一下“问题解答”在哪里。。。。

**Comment by Lssg97** [comment]
在首页ReadMe文件里可以找到啊，很大一张表格呢。
