### ISSUE TITLE
加载皮肤后在AMD处理器的电脑上CPU使用率立马上升到100%

### ISSUE THREAD

**Issue by ldqk** [Lssg97/DetailedSystemMonitor#22]
操作系统：Windows11 LTSC 24H2 26100.1742
Rainmeter版本：4.5.20.3803
皮肤版本：3.4.b Beta
![{58B6FF16-0E5A-490C-9428-1A68A78D6225}](https://github.com/user-attachments/assets/624115b1-8028-4051-8e3d-87cda22a04ac)
![{3A50A256-ACD2-48B6-9225-9C86262F6277}](https://github.com/user-attachments/assets/dee3c648-99e9-49f3-9529-85334aa52103)
![{A62B242D-56FD-432D-B0A5-FB532C934777}](https://github.com/user-attachments/assets/a4f92142-6f92-498a-af7d-c1833b2f5fc2)

**Comment by Lssg97** [comment]
您好，
皮肤是否被正确加载？加载后皮肤能否正常更新信息？如果都可以的话，我需要查看 Rainmeter 日志。

**Comment by ldqk** [comment]
皮肤能正常加载，加载后CPU就马上全核100%了，风扇狂转，但在Intel的机器上是正常的，这是日志截图
![QQ_1727006481121](https://github.com/user-attachments/assets/5718ea53-a6dc-4ff3-b20a-5df7cbde13ec)

**Comment by ldqk** [comment]
皮肤加载后的样子：![QQ_1727006578880](https://github.com/user-attachments/assets/effc76ad-44c8-408d-8aef-cc662d19c34f)

**Comment by Lssg97** [comment]
一项一项排查吧，先看看是不是 GPU 部分出的问题。

请编辑皮肤配置文件，找到第 2185-2187 行，去掉这三行开头的分号：

https://github.com/Lssg97/DetailedSystemMonitor/blob/59a1389344f367ed5048690fc351fe5538f67b06/Skin/DetailedSystemMonitor.ini#L2182-L2189

刷新皮肤后再看看是否还占用这么高的 CPU。

**Comment by ldqk** [comment]
去掉第2185-2187行的分号后加载皮肤，依旧会打满CPU，但经过我多次排查，我发现将614-755行删除后，就正常了，但皮肤显示错位了

![QQ_1727057167376](https://github.com/user-attachments/assets/55371f7b-aaf5-4b25-b88f-bcc3aec6a02c)

**Comment by ldqk** [comment]
最终排查到是Wifi配置导致的CPU打满，我把第712行注释掉就好了
https://github.com/Lssg97/DetailedSystemMonitor/blob/59a1389344f367ed5048690fc351fe5538f67b06/Skin/DetailedSystemMonitor.ini#L711-L713
![QQ_1727057824308](https://github.com/user-attachments/assets/b724ffb6-d429-4737-853d-c8e03963a6e2)

**Comment by Lssg97** [comment]
这个问题还真是第一次见到，我感觉可能是这个插件没有很好支持你的网卡。我建议你去 [Rainmeter 论坛](https://forum.rainmeter.net/)或者 [rainmeter 存储库](https://github.com/rainmeter/rainmeter)提交这个问题。
