### ISSUE TITLE
信息文字希望可以增加阴影效果

### ISSUE THREAD

**Issue by ldqk** [Lssg97/DetailedSystemMonitor#3]
信息文字希望可以增加阴影效果，这样能够让信息文字更加突出明显

**Comment by Lssg97** [comment]
文字颜色是可以修改的。

![image](https://user-images.githubusercontent.com/47817993/108467590-6b097000-72c0-11eb-8fb7-d7cb84d93616.png)

**Comment by ldqk** [comment]
颜色是可以修改，但是我想的是给文字增加阴阴效果

**Comment by Lssg97** [comment]
Rainmeter 支持给文字添加阴影，但是我个人感觉显示效果并不好看。所以我应该不会在后续更新中添加这个。如果您想要添加的话，可以自己修改配置文件。

在每个 String 节点下添加下面两行：

```
StringEffect=Shadow
FontEffectColor=100,100,100,255
```

第二行的颜色可以自己修改。

**Comment by ldqk** [comment]
好的，感谢！
