### ISSUE TITLE
显卡显存Nun

### ISSUE THREAD

**Issue by dxh000130** [Lssg97/DetailedSystemMonitor#4]
使用管理员权限运行并确定NADIA独立显卡已经运行后，显存不显示，显卡也只显示集显，显卡温度正常显示。
![屏幕截图 2021-04-28 212743](https://user-images.githubusercontent.com/34475380/116411776-9a140300-a868-11eb-9e7d-83f5b6664492.png)

**Comment by dxh000130** [comment]
NvidiaGPU已安装

**Comment by dxh000130** [comment]
显卡温度显示的好像是cpu温度

**Comment by Lssg97** [comment]
看起来是皮肤没有正确分辨出独立显卡，麻烦提供一下日志信息的下面这几项：

![image](https://user-images.githubusercontent.com/47817993/116719765-08de9100-aa0e-11eb-88df-9f4d55b7ceb2.png)

**Comment by dxh000130** [comment]
好的 我试试

**Comment by dxh000130** [comment]
> 看起来是皮肤没有正确分辨出独立显卡，麻烦提供一下日志信息的下面这几项：
> 
> ![image](https://user-images.githubusercontent.com/47817993/116719765-08de9100-aa0e-11eb-88df-9f4d55b7ceb2.png)

![896C7A92-4877-47A7-B983-E4463CD3C9DA](https://user-images.githubusercontent.com/34475380/117779043-dc7a0e80-b270-11eb-8d7f-2f8644919356.jpeg)

**Comment by Lssg97** [comment]
你的计算机设备管理器里含有一个用于支持“Link to MyASUS”服务的虚拟显卡，导致皮肤没有检测到独立显卡。我会在3.4版本更新中公开对此情况的的适配更新。

你可以通过 [**develop**](https://github.com/Lssg97/DetailedSystemMonitor/tree/develop/Skin) 分支提前获取已经适配后的版本。

感谢你的反馈！

**Comment by dxh000130** [comment]
您好 现在2060已经被识别到了 显存也正常了 但是显卡温度变成了na
![CB581F02-15DF-412C-BAE5-6490F515E7CE](https://user-images.githubusercontent.com/34475380/118096214-a325d800-b403-11eb-98d2-ee6d8f48c77f.jpeg)
![B077F6B1-9F13-4DE3-8CBD-50A5BE28D99A](https://user-images.githubusercontent.com/34475380/118096231-a8832280-b403-11eb-92f4-8d3fe946ec50.jpeg)

**Comment by Lssg97** [comment]
这个问题我前两天也遇到了，你的独立显卡应该是已经工作了，但是我猜你的显卡驱动安装的是 DCH 版本驱动（NVIDIA 控制面板不在系统的控制面板里，变成了一个独立的 UWP 程序）。

![屏幕截图 2021-05-13 191339](https://user-images.githubusercontent.com/47817993/118118707-dc6c4100-b41f-11eb-9382-41e20c8e6eb5.png)

这种版本的驱动使用的大概不是原来的 API，导致显卡温度监控插件无法获取显卡温度。我目前能给出的两个解决方案：

1. 卸载现有的 DCH 版本驱动，去下载标准版驱动（前往 [**NVIDIA 驱动程序下载**](https://www.nvidia.cn/Download/Find.aspx?lang=cn)，选择自己的显卡型号后，**Windows 驱动程序类型** 选择 **`标准`**。

![屏幕截图 2021-05-13 192324](https://user-images.githubusercontent.com/47817993/118119834-91532d80-b421-11eb-9449-dc909c01fe50.png)

2. （未经试验，不一定有效）打开 NVIDIA 控制面板，菜单栏选择 **`桌面 - 启用开发者设置`** ，然后在 **`开发者 - 管理 GPU 性能计数器`** 里选择 **`允许所有用户访问 GPU 性能计数器`** 。

![屏幕截图 2021-05-13 190921](https://user-images.githubusercontent.com/47817993/118120046-dbd4aa00-b421-11eb-9b9d-91b67a928d9e.png)

**Comment by dxh000130** [comment]
好的 我试试 谢谢

**Comment by Lssg97** [comment]
> 好的 我试试 谢谢

如何？
