### ISSUE TITLE
部件拆分

### ISSUE THREAD

**Issue by imroxe** [Lssg97/DetailedSystemMonitor#6]
可以把CPU、GPU等等各个部分分开么，尝试删除了GPU部分，结果中间有一大块空白的地方

**Comment by Lssg97** [comment]
本皮肤设计的一个小原则就是：**只用一个文件实现皮肤的全部功能。**

这样做的好处是可以防止某些关键配置文件丢失导致皮肤功能异常（这种情况常出现在一些擅自修改了 Rainmeter 的 Skins 文件夹目录架构的新人用户电脑上）；而且，皮肤内有大量节点需要获取其它监测部分节点的信息来进行逻辑判断。拆分起来既麻烦，又不方便后期维护及添加新功能；同时只有一个主体文件也算是我个人的强迫症需求（皮肤内的字体文件本身就可以通过安装到系统里的方式删除掉）。到了正在开发的 3.4 版本中，因为增加了英文版，所以把原来的用户配置参数和本地化翻译文本都拿出来建立了单独的文件，不过皮肤的主体配置文件里也做了冗余设计，保证了整个皮肤只剩下这么一个主体文件时，皮肤也能正常工作。所以**请原谅我坚持不进行拆分。**

**Comment by Lssg97** [comment]
我在最近的 [develop](../tree/develop) 分支更新中优化了一下 GPU 的监测部分，当无法准确获取显卡信息时会隐藏全部的 GPU 信息。您可以利用此更新来完美隐藏所有和 GPU 有关的信息。关于获取最新的安装包以及如何操作，您可以通过 [QQ](https://wpa.qq.com/msgrd?uin=760265690) 或[邮箱](mailto:lssg97@163.com)联系我。
