### ISSUE TITLE
显卡温度Nun

### ISSUE THREAD

**Issue by dxh000130** [Lssg97/DetailedSystemMonitor#7]
N卡，显卡驱动是标准版，也安装了插件，但显卡温度还是Nun.
![image](https://user-images.githubusercontent.com/34475380/137648749-55801a74-2141-44df-88c8-aec336dfd11b.png)

**Comment by Lssg97** [comment]
3.4 beta版本解决了这个问题 可以尝试安装 仓库develop分支已更新皮肤文件夹但rmskin安装包还未发布 可以通过QQ或邮箱与我联系所要

**Comment by dxh000130** [comment]
好的 谢谢
