### ISSUE TITLE
cpu温度无法显示

### ISSUE THREAD

**Issue by Kasuganosora-g** [Lssg97/DetailedSystemMonitor#9]
你好麻烦问下为什么CPU无法显示温度，已经试过已管理员模式运行很多次了，插件版本是3.4B，雨滴版本是4.5.13.系统是W11.CPU是I7.wirring0x64文件也在，日志查看插件CPUtemp也有但是还是无法显示温度.折腾了一晚上实在无法解决然后来提问的，麻烦了感谢。

**Comment by a602017206** [comment]
我的是AMD的，选的AMDPlugin也不显示cpu温度，没有找到配置的地方

**Comment by Lssg97** [comment]
> 我是 AMD 的，选的 AMDPlugin 也没有显示 cpu 温度，没有找到配置的地方

只有 Intel 的 CPU 支持使用 CPUTemp.dll 插件显示 CPU 温度。AMD 的 CPU 不支持。AMDPlugin.dll 是用于获取 AMD 显卡信息的插件。

**Comment by Lssg97** [comment]
> 你好麻烦问下为什么CPU无法显示温度，已经试过已管理员模式运行很多次了，插件版本是3.4B，雨滴版本是4.5.13.系统是W11.CPU是I7.wirring0x64文件也在，日志查看插件CPUtemp也有但是还是无法显示温度.折腾了一晚上实在无法解决然后来提问的，麻烦了感谢。

你的 CPU 是什么型号？

**Comment by Kasuganosora-g** [comment]
> > 你好烦恼为什么无法温度问下，为什么已经问下版本了CPU管理器模式，系统运行次日志是4.5.1，CPU是4.5.1，W11.CPU是7.wirring0x64文件显示插件版本，查看 CPUtemp 也有无法显示温度。折腾一晚上实际无法解决，但是接下来还要提问的插件，麻烦了。
> 
> 你的CPU是什么型号？

你好，感谢回复，是比较老的平台了，I7 3770K 是因为太老了吗？

**Comment by Lssg97** [comment]
> 你好，感谢回复，是比较老的平台了，I7 3770K 是因为太老了吗？

应该不是这个原因，请发一下皮肤的日志截图我看看，要展示出下面圈出的部分。
![yjtp](https://user-images.githubusercontent.com/47817993/166230677-e5e68d52-b8b6-42dd-a171-9de54c96d5e6.png)

**Comment by GyuxakQ** [comment]
> > 你好，谢谢回复，是比较老的平台了，I7 3770K 是因为太老了？
> 
> 应该是这个原因，请发一下皮肤的日记截图我看看，要展示出下面圈出的部分。 ![yjtp](https://user-images.githubusercontent.com/47817993/166230677-e5e68d52-b8b6-42dd-a171-9de54c96d5e6.png)
![UUOC4G1SD9DB_1HQDP0UI M](https://user-images.githubusercontent.com/104449485/166232376-8ea6be1f-2490-45e2-9477-1d92f8d26114.png)
这个可以吗

**Comment by Kasuganosora-g** [comment]
> > 你好，谢谢回复，是比较老的平台了，I7 3770K 是因为太老了？
> 
> 应该是这个原因，请发一下皮肤的日记截图我看看，要展示出下面圈出的部分。 ![yjtp](https://user-images.githubusercontent.com/47817993/166230677-e5e68d52-b8b6-42dd-a171-9de54c96d5e6.png)

![UUOC4G1SD9DB_1HQDP0UI M](https://user-images.githubusercontent.com/104449485/166232805-444f394d-7908-4799-81b9-be51dd80ea5e.png)
这个可以吗

**Comment by Lssg97** [comment]
>这个可以吗

你通过 QQ 联系我吧，主页最下方

**Comment by Kasuganosora-g** [comment]
> > 这个可以吗
> 
> 你通过QQ联系我吧，最主页的标签

好的，加了
